# Galaxy plot parameters

# inputFiles:
#   haloFile: 'data/SMT13HaloOutput.hdf5'
#   subhaloFile: 'data/SMT13SubhaloOutput.hdf5'
#   galaxyFile: 'data/SMT13GalaxyOutput.hdf5'
inputFiles:
  haloFile: 'data/testHaloOutput.hdf5'
  subhaloFile: 'data/testSubhaloOutput.hdf5'
  galaxyFile: 'data/testGalaxyOutput.hdf5'

 
# The following should really be attributes of the data
cosmo:
 baryonFraction: 0.155

plots:
 baryonFraction: False
 coldGas_halo: False
 coldGas_subhalo: False
 coldGasRadius: False
 stellarMass_halo: True
 stellarMass_subhalo: True
 stellarHaloMassRatio: True
 stellarSubhaloMassRatio: True
 starFormationRate: False

graphs:
 graphMin: 0
 graphMax: 1000 # Note - includes last element!
 
snapshots:
 snapMin: 61
 snapMax: 61 # Note - includes last element!

baryonFraction:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: 'Baryon fraction'

coldGas_halo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{cold gas}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gal_coldgas_halo'

coldGas_subhalo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{cold gas}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gal_coldgas_subhalo'

coldGasRadius:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$R_\mathrm{d,cold gas}$ / kpc'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gal_coldgas_radius'

stellarMass_halo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gal_stars_halo'

stellarMass_subhalo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gal_stars_sub'

stellarHaloMassRatio:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / $M_\mathrm{halo}$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gal_stars_halo_ratio'

stellarSubhaloMassRatio:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / $M_\mathrm{subhalo}$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gal_stars_sub_ratio'

starFormationRate:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: 'SFR / M$_\odot$ yr$^{-1}$'
