# Galaxy plot parameters

inputFiles:
  haloFile: 'data/test_HaloOutput.hdf5'
  subhaloFile: 'data/test_SubhaloOutput.hdf5'
  galaxyFile: 'data/test_GalaxyOutput.hdf5'
save_prefix: 'test_gal_'
 
# The following should really be attributes of the data
cosmo:
 baryonFraction: 0.155

plots:
 baryonFraction: False
 bulgeFraction: True
 blackHole_stars: True
 coldGas_halo: True
 coldGas_subhalo: True
 coldGasMetallicity: True
 coldGasRadius: True
 SFR: True
 sSFR: True
 stellarMass_halo: True
 stellarMass_subhalo: True
 stellarHaloMassRatio: True
 stellarSubhaloMassRatio: True
 stellarDiscRadius: True
 stellarDiscMetallicity: True

graphs:
 graphMin: 0
 graphMax: 1000 # Note - includes last element!
 
snapshots:
 snapMin: 61
 snapMax: 61 # Note - includes last element!

baryonFraction:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: 'Baryon fraction'
 legend:  True
 label:   'Universal baryon fraction'
 save_png: True
 save_pdf: False
 name:    'bfrac'

blackHole_stars:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{BH}$ / M$_\odot$'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'BH_stars'

bulgeFraction:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: 'Bulge/total stellar fraction'
 legend:   False
 label:   ' '
 save_png: True
 save_pdf: False
 name:    'bulge_fraction'

coldGas_halo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{cold gas}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'coldgas_halo'

coldGas_subhalo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{cold gas}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'coldgas_subhalo'

coldGasRadius:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$'
 ylabel: '$R_\mathrm{d,cold gas}$ / kpc'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gas_disc_radius'

stellarDiscRadius:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$R_\mathrm{d,stellar disc}$ / kpc'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stellar_disc_radius'

stellarMass_halo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stars_halo'

stellarMass_subhalo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stars_sub'

stellarHaloMassRatio:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / $M_\mathrm{halo}$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stars_halo_ratio'

stellarSubhaloMassRatio:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / $M_\mathrm{subhalo}$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stars_sub_ratio'

coldGasMetallicity:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$Z_\mathrm{cold gas}$'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gas_disc_Z'

SFR:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$'
 ylabel: 'SFR / M$_\odot$ yr$^{-1}$'
 legend:   True
 label:   'In last timestep'
 save_png: True
 save_pdf: False
 name:    'SFR'

sSFR:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$'
 ylabel: 'SFR / yr$^{-1}$'
 legend:   True
 label:   'In last timestep'
 save_png: True
 save_pdf: False
 name:    'sSFR'

stellarDiscMetallicity:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$Z_\mathrm{stellar disc}$'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stellar_disc_Z'

