# Galaxy plot parameters

inputFiles:
  haloFile: 'data/AGNfeed_HaloOutput.hdf5'
  subhaloFile: 'data/AGNfeed_SubhaloOutput.hdf5'
  galaxyFile: 'data/AGNfeed_GalaxyOutput.hdf5'
save_prefix: 'AGNfeed_gal_'
 
# The following should really be attributes of the data
cosmo:
 baryonFraction: 0.155

plots:
 baryonFraction: False
 blackHole_stars: True
 coldGas_halo: False
 coldGas_subhalo: False
 coldGasMetallicity: True
 coldGasRadius: True
 starFormationRate: False
 stellarMass_halo: False
 stellarMass_subhalo: True
 stellarHaloMassRatio: False
 stellarSubhaloMassRatio: False
 stellarDiscRadius: True
 stellarDiscMetallicity: True

graphs:
 graphMin: 0
 graphMax: 1000 # Note - includes last element!
 
snapshots:
 snapMin: 61
 snapMax: 61 # Note - includes last element!

baryonFraction:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: 'Baryon fraction'

blackHole_stars:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{BH}$ / M$_\odot$'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'BH_stars'

coldGas_halo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{cold gas}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'coldgas_halo'

coldGas_subhalo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{cold gas}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'coldgas_subhalo'

coldGasRadius:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$'
 ylabel: '$R_\mathrm{d,cold gas}$ / kpc'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gas_disc_radius'

stellarDiscRadius:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$R_\mathrm{d,stellar disc}$ / kpc'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stellar_disc_radius'

stellarMass_halo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stars_halo'

stellarMass_subhalo:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / M$_\odot$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stars_sub'

stellarHaloMassRatio:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / $M_\mathrm{halo}$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stars_halo_ratio'

stellarSubhaloMassRatio:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_\mathrm{subhalo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$M_\mathrm{stars}$ / $M_\mathrm{subhalo}$'
 legend:   True
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stars_sub_ratio'

coldGasMetallicity:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$Z_\mathrm{cold gas}$'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'gas_disc_Z'

stellarDiscMetallicity:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'linear'
 markerType: '.'
 xlabel: '$M_*$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: '$Z_\mathrm{stellar disc}$'
 legend:   False
 label:   'SAM galaxies'
 save_png: True
 save_pdf: False
 name:    'stellar_disc_Z'

starFormationRate:
 figsize: [12,8]
 xscale: 'log'
 yscale: 'log'
 markerType: '.'
 xlabel: '$M_\mathrm{halo}$ / M$_\odot$' # Units should really be an attribute of the data
 ylabel: 'SFR / M$_\odot$ yr$^{-1}$'
